/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToursIndexRouteImport } from './routes/tours.index'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ToursSlugRouteImport } from './routes/tours.$slug'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminToursIndexRouteImport } from './routes/admin.tours.index'
import { Route as AdminBlogIndexRouteImport } from './routes/admin.blog.index'
import { Route as AdminToursIdRouteImport } from './routes/admin.tours.$id'
import { Route as AdminBlogIdRouteImport } from './routes/admin.blog.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursIndexRoute = ToursIndexRouteImport.update({
  id: '/tours/',
  path: '/tours/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursSlugRoute = ToursSlugRouteImport.update({
  id: '/tours/$slug',
  path: '/tours/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminToursIndexRoute = AdminToursIndexRouteImport.update({
  id: '/admin/tours/',
  path: '/admin/tours/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/admin/blog/',
  path: '/admin/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminToursIdRoute = AdminToursIdRouteImport.update({
  id: '/admin/tours/$id',
  path: '/admin/tours/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogIdRoute = AdminBlogIdRouteImport.update({
  id: '/admin/blog/$id',
  path: '/admin/blog/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/login': typeof AdminLoginRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/tours/$slug': typeof ToursSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/tours/': typeof ToursIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/tours/$id': typeof AdminToursIdRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/tours/': typeof AdminToursIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/login': typeof AdminLoginRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/tours/$slug': typeof ToursSlugRoute
  '/admin': typeof AdminIndexRoute
  '/journal': typeof JournalIndexRoute
  '/tours': typeof ToursIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/tours/$id': typeof AdminToursIdRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/tours': typeof AdminToursIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/login': typeof AdminLoginRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/tours/$slug': typeof ToursSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/tours/': typeof ToursIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/tours/$id': typeof AdminToursIdRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/tours/': typeof AdminToursIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/sitemap.xml'
    | '/admin/login'
    | '/journal/$slug'
    | '/tours/$slug'
    | '/admin/'
    | '/journal/'
    | '/tours/'
    | '/admin/blog/$id'
    | '/admin/tours/$id'
    | '/admin/blog/'
    | '/admin/tours/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/sitemap.xml'
    | '/admin/login'
    | '/journal/$slug'
    | '/tours/$slug'
    | '/admin'
    | '/journal'
    | '/tours'
    | '/admin/blog/$id'
    | '/admin/tours/$id'
    | '/admin/blog'
    | '/admin/tours'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/sitemap.xml'
    | '/admin/login'
    | '/journal/$slug'
    | '/tours/$slug'
    | '/admin/'
    | '/journal/'
    | '/tours/'
    | '/admin/blog/$id'
    | '/admin/tours/$id'
    | '/admin/blog/'
    | '/admin/tours/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminLoginRoute: typeof AdminLoginRoute
  JournalSlugRoute: typeof JournalSlugRoute
  ToursSlugRoute: typeof ToursSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  JournalIndexRoute: typeof JournalIndexRoute
  ToursIndexRoute: typeof ToursIndexRoute
  AdminBlogIdRoute: typeof AdminBlogIdRoute
  AdminToursIdRoute: typeof AdminToursIdRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
  AdminToursIndexRoute: typeof AdminToursIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/': {
      id: '/tours/'
      path: '/tours'
      fullPath: '/tours/'
      preLoaderRoute: typeof ToursIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/$slug': {
      id: '/tours/$slug'
      path: '/tours/$slug'
      fullPath: '/tours/$slug'
      preLoaderRoute: typeof ToursSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tours/': {
      id: '/admin/tours/'
      path: '/admin/tours'
      fullPath: '/admin/tours/'
      preLoaderRoute: typeof AdminToursIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/admin/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tours/$id': {
      id: '/admin/tours/$id'
      path: '/admin/tours/$id'
      fullPath: '/admin/tours/$id'
      preLoaderRoute: typeof AdminToursIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog/$id': {
      id: '/admin/blog/$id'
      path: '/admin/blog/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AdminBlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminLoginRoute: AdminLoginRoute,
  JournalSlugRoute: JournalSlugRoute,
  ToursSlugRoute: ToursSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  JournalIndexRoute: JournalIndexRoute,
  ToursIndexRoute: ToursIndexRoute,
  AdminBlogIdRoute: AdminBlogIdRoute,
  AdminToursIdRoute: AdminToursIdRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
  AdminToursIndexRoute: AdminToursIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
