/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminCustomBuilderRouteImport } from './routes/admin.custom-builder'
import { Route as AdminFaqsRouteImport } from './routes/admin.faqs'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as BookingCancelledRouteImport } from './routes/booking.cancelled'
import { Route as BookingManageRouteImport } from './routes/booking.manage'
import { Route as BookingSuccessRouteImport } from './routes/booking.success'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as LisbonGuideIndexRouteImport } from './routes/lisbon-guide.index'
import { Route as ToursIndexRouteImport } from './routes/tours.index'
import { Route as ToursSlugRouteImport } from './routes/tours.$slug'
import { Route as ToursCustomRouteImport } from './routes/tours.custom'
import { Route as ToursPricingGuideRouteImport } from './routes/tours.pricing-guide'
import { Route as AdminBlogIndexRouteImport } from './routes/admin.blog.index'
import { Route as AdminBlogIdRouteImport } from './routes/admin.blog.$id'
import { Route as AdminToursIndexRouteImport } from './routes/admin.tours.index'
import { Route as AdminToursIdRouteImport } from './routes/admin.tours.$id'
import { Route as ApiPublicBookingsRouteImport } from './routes/api/public/bookings'
import { Route as ApiPublicPaymentsMollieRouteImport } from './routes/api/public/payments/mollie'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/admin/bookings',
  path: '/admin/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomBuilderRoute = AdminCustomBuilderRouteImport.update({
  id: '/admin/custom-builder',
  path: '/admin/custom-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFaqsRoute = AdminFaqsRouteImport.update({
  id: '/admin/faqs',
  path: '/admin/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/admin/messages',
  path: '/admin/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/admin/reviews',
  path: '/admin/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingCancelledRoute = BookingCancelledRouteImport.update({
  id: '/booking/cancelled',
  path: '/booking/cancelled',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingManageRoute = BookingManageRouteImport.update({
  id: '/booking/manage',
  path: '/booking/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingSuccessRoute = BookingSuccessRouteImport.update({
  id: '/booking/success',
  path: '/booking/success',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LisbonGuideIndexRoute = LisbonGuideIndexRouteImport.update({
  id: '/lisbon-guide/',
  path: '/lisbon-guide/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursIndexRoute = ToursIndexRouteImport.update({
  id: '/tours/',
  path: '/tours/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursSlugRoute = ToursSlugRouteImport.update({
  id: '/tours/$slug',
  path: '/tours/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursCustomRoute = ToursCustomRouteImport.update({
  id: '/tours/custom',
  path: '/tours/custom',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursPricingGuideRoute = ToursPricingGuideRouteImport.update({
  id: '/tours/pricing-guide',
  path: '/tours/pricing-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/admin/blog/',
  path: '/admin/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogIdRoute = AdminBlogIdRouteImport.update({
  id: '/admin/blog/$id',
  path: '/admin/blog/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminToursIndexRoute = AdminToursIndexRouteImport.update({
  id: '/admin/tours/',
  path: '/admin/tours/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminToursIdRoute = AdminToursIdRouteImport.update({
  id: '/admin/tours/$id',
  path: '/admin/tours/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBookingsRoute = ApiPublicBookingsRouteImport.update({
  id: '/api/public/bookings',
  path: '/api/public/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsMollieRoute = ApiPublicPaymentsMollieRouteImport.update({
  id: '/api/public/payments/mollie',
  path: '/api/public/payments/mollie',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/custom-builder': typeof AdminCustomBuilderRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/booking/cancelled': typeof BookingCancelledRoute
  '/booking/manage': typeof BookingManageRoute
  '/booking/success': typeof BookingSuccessRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/tours/$slug': typeof ToursSlugRoute
  '/tours/custom': typeof ToursCustomRoute
  '/tours/pricing-guide': typeof ToursPricingGuideRoute
  '/admin/': typeof AdminIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/lisbon-guide/': typeof LisbonGuideIndexRoute
  '/tours/': typeof ToursIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/tours/$id': typeof AdminToursIdRoute
  '/api/public/bookings': typeof ApiPublicBookingsRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/tours/': typeof AdminToursIndexRoute
  '/api/public/payments/mollie': typeof ApiPublicPaymentsMollieRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/custom-builder': typeof AdminCustomBuilderRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/booking/cancelled': typeof BookingCancelledRoute
  '/booking/manage': typeof BookingManageRoute
  '/booking/success': typeof BookingSuccessRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/tours/$slug': typeof ToursSlugRoute
  '/tours/custom': typeof ToursCustomRoute
  '/tours/pricing-guide': typeof ToursPricingGuideRoute
  '/admin': typeof AdminIndexRoute
  '/journal': typeof JournalIndexRoute
  '/lisbon-guide': typeof LisbonGuideIndexRoute
  '/tours': typeof ToursIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/tours/$id': typeof AdminToursIdRoute
  '/api/public/bookings': typeof ApiPublicBookingsRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/tours': typeof AdminToursIndexRoute
  '/api/public/payments/mollie': typeof ApiPublicPaymentsMollieRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/custom-builder': typeof AdminCustomBuilderRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/booking/cancelled': typeof BookingCancelledRoute
  '/booking/manage': typeof BookingManageRoute
  '/booking/success': typeof BookingSuccessRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/tours/$slug': typeof ToursSlugRoute
  '/tours/custom': typeof ToursCustomRoute
  '/tours/pricing-guide': typeof ToursPricingGuideRoute
  '/admin/': typeof AdminIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/lisbon-guide/': typeof LisbonGuideIndexRoute
  '/tours/': typeof ToursIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/tours/$id': typeof AdminToursIdRoute
  '/api/public/bookings': typeof ApiPublicBookingsRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/tours/': typeof AdminToursIndexRoute
  '/api/public/payments/mollie': typeof ApiPublicPaymentsMollieRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/privacy'
    | '/reviews'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/bookings'
    | '/admin/custom-builder'
    | '/admin/faqs'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/orders'
    | '/admin/reviews'
    | '/admin/settings'
    | '/booking/cancelled'
    | '/booking/manage'
    | '/booking/success'
    | '/journal/$slug'
    | '/tours/$slug'
    | '/tours/custom'
    | '/tours/pricing-guide'
    | '/admin/'
    | '/journal/'
    | '/lisbon-guide/'
    | '/tours/'
    | '/admin/blog/$id'
    | '/admin/tours/$id'
    | '/api/public/bookings'
    | '/admin/blog/'
    | '/admin/tours/'
    | '/api/public/payments/mollie'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/privacy'
    | '/reviews'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/bookings'
    | '/admin/custom-builder'
    | '/admin/faqs'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/orders'
    | '/admin/reviews'
    | '/admin/settings'
    | '/booking/cancelled'
    | '/booking/manage'
    | '/booking/success'
    | '/journal/$slug'
    | '/tours/$slug'
    | '/tours/custom'
    | '/tours/pricing-guide'
    | '/admin'
    | '/journal'
    | '/lisbon-guide'
    | '/tours'
    | '/admin/blog/$id'
    | '/admin/tours/$id'
    | '/api/public/bookings'
    | '/admin/blog'
    | '/admin/tours'
    | '/api/public/payments/mollie'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/privacy'
    | '/reviews'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/bookings'
    | '/admin/custom-builder'
    | '/admin/faqs'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/orders'
    | '/admin/reviews'
    | '/admin/settings'
    | '/booking/cancelled'
    | '/booking/manage'
    | '/booking/success'
    | '/journal/$slug'
    | '/tours/$slug'
    | '/tours/custom'
    | '/tours/pricing-guide'
    | '/admin/'
    | '/journal/'
    | '/lisbon-guide/'
    | '/tours/'
    | '/admin/blog/$id'
    | '/admin/tours/$id'
    | '/api/public/bookings'
    | '/admin/blog/'
    | '/admin/tours/'
    | '/api/public/payments/mollie'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  FaqRoute: typeof FaqRoute
  PrivacyRoute: typeof PrivacyRoute
  ReviewsRoute: typeof ReviewsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCustomBuilderRoute: typeof AdminCustomBuilderRoute
  AdminFaqsRoute: typeof AdminFaqsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  BookingCancelledRoute: typeof BookingCancelledRoute
  BookingManageRoute: typeof BookingManageRoute
  BookingSuccessRoute: typeof BookingSuccessRoute
  JournalSlugRoute: typeof JournalSlugRoute
  ToursSlugRoute: typeof ToursSlugRoute
  ToursCustomRoute: typeof ToursCustomRoute
  ToursPricingGuideRoute: typeof ToursPricingGuideRoute
  AdminIndexRoute: typeof AdminIndexRoute
  JournalIndexRoute: typeof JournalIndexRoute
  LisbonGuideIndexRoute: typeof LisbonGuideIndexRoute
  ToursIndexRoute: typeof ToursIndexRoute
  AdminBlogIdRoute: typeof AdminBlogIdRoute
  AdminToursIdRoute: typeof AdminToursIdRoute
  ApiPublicBookingsRoute: typeof ApiPublicBookingsRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
  AdminToursIndexRoute: typeof AdminToursIndexRoute
  ApiPublicPaymentsMollieRoute: typeof ApiPublicPaymentsMollieRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/admin/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/custom-builder': {
      id: '/admin/custom-builder'
      path: '/admin/custom-builder'
      fullPath: '/admin/custom-builder'
      preLoaderRoute: typeof AdminCustomBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/faqs': {
      id: '/admin/faqs'
      path: '/admin/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AdminFaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/admin/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/cancelled': {
      id: '/booking/cancelled'
      path: '/booking/cancelled'
      fullPath: '/booking/cancelled'
      preLoaderRoute: typeof BookingCancelledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/manage': {
      id: '/booking/manage'
      path: '/booking/manage'
      fullPath: '/booking/manage'
      preLoaderRoute: typeof BookingManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/success': {
      id: '/booking/success'
      path: '/booking/success'
      fullPath: '/booking/success'
      preLoaderRoute: typeof BookingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lisbon-guide/': {
      id: '/lisbon-guide/'
      path: '/lisbon-guide'
      fullPath: '/lisbon-guide/'
      preLoaderRoute: typeof LisbonGuideIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/': {
      id: '/tours/'
      path: '/tours'
      fullPath: '/tours/'
      preLoaderRoute: typeof ToursIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/$slug': {
      id: '/tours/$slug'
      path: '/tours/$slug'
      fullPath: '/tours/$slug'
      preLoaderRoute: typeof ToursSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/custom': {
      id: '/tours/custom'
      path: '/tours/custom'
      fullPath: '/tours/custom'
      preLoaderRoute: typeof ToursCustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/pricing-guide': {
      id: '/tours/pricing-guide'
      path: '/tours/pricing-guide'
      fullPath: '/tours/pricing-guide'
      preLoaderRoute: typeof ToursPricingGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/admin/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog/$id': {
      id: '/admin/blog/$id'
      path: '/admin/blog/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AdminBlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tours/': {
      id: '/admin/tours/'
      path: '/admin/tours'
      fullPath: '/admin/tours/'
      preLoaderRoute: typeof AdminToursIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tours/$id': {
      id: '/admin/tours/$id'
      path: '/admin/tours/$id'
      fullPath: '/admin/tours/$id'
      preLoaderRoute: typeof AdminToursIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bookings': {
      id: '/api/public/bookings'
      path: '/api/public/bookings'
      fullPath: '/api/public/bookings'
      preLoaderRoute: typeof ApiPublicBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/mollie': {
      id: '/api/public/payments/mollie'
      path: '/api/public/payments/mollie'
      fullPath: '/api/public/payments/mollie'
      preLoaderRoute: typeof ApiPublicPaymentsMollieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  FaqRoute: FaqRoute,
  PrivacyRoute: PrivacyRoute,
  ReviewsRoute: ReviewsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCustomBuilderRoute: AdminCustomBuilderRoute,
  AdminFaqsRoute: AdminFaqsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  BookingCancelledRoute: BookingCancelledRoute,
  BookingManageRoute: BookingManageRoute,
  BookingSuccessRoute: BookingSuccessRoute,
  JournalSlugRoute: JournalSlugRoute,
  ToursSlugRoute: ToursSlugRoute,
  ToursCustomRoute: ToursCustomRoute,
  ToursPricingGuideRoute: ToursPricingGuideRoute,
  AdminIndexRoute: AdminIndexRoute,
  JournalIndexRoute: JournalIndexRoute,
  LisbonGuideIndexRoute: LisbonGuideIndexRoute,
  ToursIndexRoute: ToursIndexRoute,
  AdminBlogIdRoute: AdminBlogIdRoute,
  AdminToursIdRoute: AdminToursIdRoute,
  ApiPublicBookingsRoute: ApiPublicBookingsRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
  AdminToursIndexRoute: AdminToursIndexRoute,
  ApiPublicPaymentsMollieRoute: ApiPublicPaymentsMollieRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
